### ISSUE TITLE
Sending render  to Mongodb instead of X11

### ISSUE THREAD

**Issue by Steven-Harris** [sillsdev/rapuma#5]
I am looking in rapuma to try to re-route the output stream to save to our mongodb at the point where it would normally display the pdf to the screen using X11. I wanted to know if you had any suggestions about doing so.

**Comment by thresherdj** [comment]
I'm sure I will not be of much help but I won't mind following along to get an idea of how this will work. Rapuma outputs a PDF so I don't know how that could be called a stream. It's more like a block of ice. :-)

 know Rapuma has the ability to output just small portions of the total amount rendered, as small as one page. I thought the output was to be picked up by the interface and then magically converted to something that would output to screen. Is Mongodb different? What is it, anyway? If you really are trying to do something live with the output from XeTeX, that is going to require something completely separate from Rapuma. Some kind of back-end to XeTeX will be needed to draw data from the output stream in real time. That is way beyond Rapuma.

**Comment by Steven-Harris** [comment]
I really just want to grab the pdf as it comes out and save it to the db. Can you point me to the location were that would occur? I am having trouble finding it in the code.

**Comment by thresherdj** [comment]
The output is like pizza. You can have it delivered to wherever you want. For example:
rapuma process KYU-MYMR-KYUMTEST component render --group GOSPEL --cid_list jhn --save --background --doc_info --override "/home/dennis/Publishing/test.pdf"

This puts the PDF output file in my Publishing folder. I think that is what you want. The --override command is probably not the most intuitive name but it was all I could think of at the time. If you think of something else to call it, I could rename it if you want, it's not like many people are using it. :-)

**Comment by Steven-Harris** [comment]
Hmm, yeah I will have to look at it. Idk if will except mongodb stuff. Do you know where that code is located?

**Comment by thresherdj** [comment]
Sorry for my ignorance but I don't know what mongodb is. It is not something I'm familiar with in my coding.

**Comment by Steven-Harris** [comment]
Oh! No worries. It is a document oriented database and our project utilizes
it.

**Comment by mhosken** [comment]
Dear Dennis,

> The output is like pizza. You can have it delivered to wherever you want. For example:
> rapuma process KYU-MYMR-KYUMTEST component render --group GOSPEL --cid_list jhn --save --background --doc_info --override "/home/dennis/Publishing/test.pdf"
> 
> This puts the PDF output file in my Publishing folder. I think that is what you want. The --override command is probably not the most intuitive name but it was all I could think of at the time. If you think of something else to call it, I could rename it if you want, it's not like many people are using it. :-)

I think what Steve is after is to replace the evince command call with his own script. I assume there's some kind of config for that.

GB,
Martin

**Comment by cambell-prince** [comment]
Saving it as a file in an arbitrary location that is passed in should be fine.

**Comment by Steven-Harris** [comment]
Where in the source code should I look?

**Comment by thresherdj** [comment]
Ah, okay, that makes sense. However, the --override command is still key to the equation. With that in place, the command to change the direction of the output from evince to another external application would be found, currently, in the rapuma.conf file. The line to change would be: pdfViewerCommand = evince, -w

Changing that to whatever is necessary will allow Rapuma to feed the PDF to the replacement app. Right now the rapuma.conf file is found in .config/rapuma in the home directory by default and in Steve's case, in a web app, it should be in /var/lib/rapuma/config. Edit the above to whatever it needs to be in that case and it should work.

Having said that, I need to point out that I am in the process of moving the settings in rapuma.conf of the system.ini file so that it will always be located in one place. This will add an extra complication to the installation but that shouldn't be too bad to deal with.

**Comment by megahirt** [comment]
Steve,

If you are referring to the scripture forge source code, I would ideally
like the rapuma project files, inputs and outputs (like PDF files) to be
stored in the project's asset folder.  If you look on the ProjectModel,
there is a getAssetsFolderPath() method.  Anything you create inside there,
including subfolders, belongs to the project.

Is that what you're asking?

Chris

**Comment by Steven-Harris** [comment]
Yes that could work for now. I will try to use that. However, later we might have to figure out a repository like system so that users can see past renders and not just the current one. As rapuma current overrights the rendered pdf everytime

**Comment by megahirt** [comment]
Steven,

You're on the right track.  Your code should manage each individual render
and make sure that past renders do not get overwritten.  So, each run of
rapuma should be passed a unique output file name that guarantees it will
not be used again.  Including the current timestamp (with second
resolution) in the file name should be adequate.  No formal repository
should be necessary.  All of the outputs of each run can sit alongside each
other in the same directory, or you could even organize each run into its
own subfolder.  That might be nice too.

Chris

**Comment by Steven-Harris** [comment]
Ahhh, that's a great idea!
