### ISSUE TITLE
Eliminating the rapuma.conf file

### ISSUE THREAD

**Issue by thresherdj** [sillsdev/rapuma#6]
There were issues with accessing the rapuma.conf file when running in a web environment. In response to that, I looked into the possibility of eliminating that file and changing the way Rapuma is installed. I now have a revision to this effect on personal/dennis. The installme file explains what needs to be done now when installing the system. Steve, would you please test this (do a fresh install) and let me know if this is more what you would want to see. If not, it shouldn't be hard for me to back out now. I'm not comfortable with no longer having a rapuma.conf file in the usual ~/.config/rapuma location but that was for use in the CLI context. If this new arrangement is a good compromise for both environments, I'll be fine with it. Let me know what you think.

**Comment by Steven-Harris** [comment]
Hey Dennis, sorry I just saw this. Thank you for working on this for me. It looks like this will help out a lot. 

However, I did run into a couple of errors when testing it using /resource/testing/kyum-example.sh they're not huge issues but I thought I would make sure you know about them.

1) 

> rapuma setting KYU-MYMR-KYUMTEST macro --section Macros/usfmTex_20160312/Columns --key > columnGutterFactor --value 20
> 
> ```
>   Welcome to Rapuma (Rapid Publication Manager)
> 
>       Version v0.7.197 testing(20160316051305)
> ```
> 
> ERR - Big problem here. Section
> [Macros/usfmTex_20160312/Columns] seems to be missing from
> configuration file.
> 
> Sorry, I have to stop. Rapuma halting now!
> 
> rapuma setting KYU-MYMR-KYUMTEST macro --section Macros/usfmTex_20160312/Columns --key > columnGutterRuleSkip --value 4
> 
> ```
>   Welcome to Rapuma (Rapid Publication Manager)
> 
>       Version v0.7.197 testing(20160316051305)
> ```
> 
> ERR - Big problem here. Section
> [Macros/usfmTex_20160312/Columns] seems to be missing from
> configuration file.
> 
> Sorry, I have to stop. Rapuma halting now!
> 
> # Verse number display
> 
> rapuma setting KYU-MYMR-KYUMTEST macro --section Macros/usfmTex_20160312/ChapterVerse  --key useMarginalVerses --value True
> 
> ```
>   Welcome to Rapuma (Rapid Publication Manager)
> 
>       Version v0.7.197 testing(20160316051305)
> ```
> 
> ERR - Big problem here. Section
> [Macros/usfmTex_20160312/ChapterVerse] seems to be missing
> from configuration file.
> 
> Sorry, I have to stop. Rapuma halting now!

2) 

> # Footnotes
> 
> rapuma setting KYU-MYMR-KYUMTEST macro --section Macros/usfmTex_20160312/Footnotes --key defineFootnoteRule --value "\hrule height 2pt\smallskip"
> 
> ```
>   Welcome to Rapuma (Rapid Publication Manager)
> 
>       Version v0.7.197 testing(20160316051305)
> ```
> 
> ERR - Big problem here. Section
> [Macros/usfmTex_20160312/Footnotes] seems to be missing from
> configuration file.
> 
> Sorry, I have to stop. Rapuma halting now!
> 
> rapuma setting KYU-MYMR-KYUMTEST macro --section Macros/usfmTex_20160312/Footnotes --key footnoteRuleOn --value "[config:macroConfig|Macros|[self:macPackId]|Footnotes|defineFootnoteRule]"
> 
> ```
>   Welcome to Rapuma (Rapid Publication Manager)
> 
>       Version v0.7.197 testing(20160316051305)
> ```
> 
> ERR - Big problem here. Section
> [Macros/usfmTex_20160312/Footnotes] seems to be missing from
> configuration file.
> 
> Sorry, I have to stop. Rapuma halting now!

3) 

> # Component Level
> 
> rapuma process KYU-MYMR-KYUMTEST component render --group GOSPEL --cid_list jhn --background --doc_info --save
> 
> ```
>   Welcome to Rapuma (Rapid Publication Manager)
> 
>       Version v0.7.197 testing(20160316051305)
> ```
> 
> Traceback (most recent call last):
>  File "/usr/local/bin/rapuma", line 902, in <module>
>     userArguments(parser.parse_args())
>   File "/usr/local/bin/rapuma", line 668, in userArguments
>     Project(pid, gid).renderGroup(cidList, pages, override, save)
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/project.py", line 185, in renderGroup
>     self.createGroup().render(self.gid, cidList, pages, override, save)
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/group/usfm.py", line 191, in render
>    self.project.managers['usfm_' + self.renderer.capitalize()].run(gid, cidList, pages, override, save)
>  File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 636, in run
>    self.makeSettingsTexFile()
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 350, in makeSettingsTexFile
>     result.append(self.affirm(i))
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 407, in affirm
>     realBool = self.returnConfRefValue(boolDependInfo['#text']).lower()
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 429, in returnConfRefValue
>     return eval(''.join(dct))
>  File "<string>", line 1, in <module>
> AttributeError: 'Xetex' object has no attribute 'macPackConfig'
> 
> # Group Level
> 
> rapuma process KYU-MYMR-KYUMTEST group render --group GOSPEL
> 
> ```
>   Welcome to Rapuma (Rapid Publication Manager)
> 
>       Version v0.7.197 testing(20160316051305)
> ```
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/rapuma", line 902, in <module>
>     userArguments(parser.parse_args())
>   File "/usr/local/bin/rapuma", line 701, in userArguments
>     Project(pid, gid).renderGroup(None, pages, override, save)
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/project.py", line 185, in renderGroup
>     self.createGroup().render(self.gid, cidList, pages, override, save)
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/group/usfm.py", line 191, in render
>     self.project.managers['usfm_' + self.renderer.capitalize()].run(gid, cidList, pages, override, save)
>  File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 636, in run
>   self.makeSettingsTexFile()
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 350, in makeSettingsTexFile
>     result.append(self.affirm(i))
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 407, in affirm
>     realBool = self.returnConfRefValue(boolDependInfo['#text']).lower()
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 429, in returnConfRefValue
>     return eval(''.join(dct))
>  File "<string>", line 1, in <module>
> AttributeError: 'Xetex' object has no attribute 'macPackConfig'
> rapuma process KYU-MYMR-KYUMTEST group render --group FOURTEES
> 
> ```
>   Welcome to Rapuma (Rapid Publication Manager)
> 
>       Version v0.7.197 testing(20160316051305)
> ```
> 
> Traceback (most recent call last):
>  File "/usr/local/bin/rapuma", line 902, in <module>
>   userArguments(parser.parse_args())
> 
>   File "/usr/local/bin/rapuma", line 701, in userArguments
>     Project(pid, gid).renderGroup(None, pages, override, save)
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/project.py", line 185, in renderGroup
>     self.createGroup().render(self.gid, cidList, pages, override, save)
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/group/usfm.py", line 191, in render
>     self.project.managers['usfm_' + self.renderer.capitalize()].run(gid, cidList, pages, override, save)
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 636, in run
>     self.makeSettingsTexFile()
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 350, in 
> 
> makeSettingsTexFile
>     result.append(self.affirm(i))
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 407, in affirm
>     realBool = self.returnConfRefValue(boolDependInfo['#text']).lower()
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 429, in returnConfRefValue
>     return eval(''.join(dct))
>   File "<string>", line 1, in <module>
> AttributeError: 'Xetex' object has no attribute 'macPackConfig'

number 3 is obviously the main issue I don't think we will need the other ones to work for now.

**Comment by Steven-Harris** [comment]
Also, I am trying to fiugre out the component shortcut as described in the tutorial documents(in both the new and the old versions). The one that allows for the user not to enter the cid_list parm. I am doing something like this... 

```
rapuma content KYU-MYMR-KYUMTEST component add --group GOSPEL  --path ~/Publishing/my_source/KYUM/PT-source
```

Is that not correct?

**Comment by thresherdj** [comment]
@Steven-Harris : There's a real problem here. Something changes when I access the config from inside /usr. The way I was normally testing showed now problems. When I tested from a different location, it failed. I don't know why, I'll need to look into it more. As I said before, having the program config in with the program itself doesn't seem like the right thing to do, but I'm not sure why, other than it isn't working. I'll look into it further as soon as I can. All the problems you are having may stem from this issue, but right now I don't know. I just know I have to get this resolved first.

**Comment by Steven-Harris** [comment]
I can get Rapuma to work just fine without this enhancement. So no need to
worry too much about this.

**Comment by thresherdj** [comment]
Ok, I think I'll revert back to the way it was, but a little cleaner, hopefully. Then you can give it a try.

**Comment by thresherdj** [comment]
Just to be sure, I'll point Rapuma to /var/lib/rapuma/config/rapuma.conf for a server-side deployment. From there, you will point it to wherever you want the Publication folder to be, okay?

**Comment by Steven-Harris** [comment]
Yep. I am actually using the publishing folder at
/var/lib/Rapuma/publishing and then overriding the renders to another
location. It will probably stay like that usually I get told otherwise.

**Comment by Steven-Harris** [comment]
@thresherdj, I think I found a bug. Rapama is requiring me to create a ".config" folder in my users' folder before I can use it.

**Comment by thresherdj** [comment]
Sorry about that, I'll look into it. I'm not sure how to do this. You will need a config folder to put the rapuma.conf file in. I thought it was going to  /var/lib/rapuma/config, What is the path where it wants to put it?

**Comment by Steven-Harris** [comment]
After making the directory myself, it put the config in
/var/www/.config/rapuma. I also had to make a folder at /var/www/.local/
for a python directory for some reason.

**Comment by thresherdj** [comment]
I don't get that. How hard would it be for me to install the web version on a virtual machine. I've never done it before but until I can see the process happen, its going to be hard to fix it.

**Comment by thresherdj** [comment]
Could I get a hold of a VM that I could set up from scratch along with all the setup scripts or whatever is used?

**Comment by Steven-Harris** [comment]
If you're familiar with vagrant here is the one that we use
http://downloads.sil.org/vagrant/Vagrantfile

**Comment by thresherdj** [comment]
That looks over my pay grade, but I'll give it a try. What VM app do you use? Would you have a clean copy of the VM you use that I could have. I have a Mint 17 VM but I don't know if that will work well for a server side application.

**Comment by Steven-Harris** [comment]
Forgive me if I am telling you something that you already know. Here is a
place to get started with Vagrant:
https://www.vagrantup.com/docs/installation/

We use Virtualbox with vagrant.

**Comment by thresherdj** [comment]
Ok, I think I got the right VM up and running. What's the user name and pass word I need to get into it?

**Comment by Steven-Harris** [comment]
You just use '''vagrant up''' from terminal to launch it. It should auto
login

**Comment by thresherdj** [comment]
I guess I'm not sure what I did wrong, maybe I installed the wrong VM. The machine comes up in tty1 and at the prompt I get "vagrant-ubuntu-trusty-64 login:"
I thought I was using the script you gave me but maybe I didn't do something right when I was fumbling around trying to get Vagrant running. Using the script you gave me, what's the incantation to reinstall the SIL VM server?

**Comment by Steven-Harris** [comment]
"cd" into where every you have your VagrantFile and you can use `vagrant destroy` to uninstall the box. The use `vagrant up` to reinstall. make sure you select/use virtualBox as your VM environment

**Comment by thresherdj** [comment]
Thanks, I think that was it. I must have installed a default system by mistake. It's downloading  one from sil.org now. I'll let you know how it goes later.

**Comment by Steven-Harris** [comment]
Yeah, you will want to goto http://downloads.sil.org/vagrant download the vagrantFile somewhere

**Comment by thresherdj** [comment]
So, I'm trying to git rapuma with this:
git clone https://github.com/sillsdev/rapuma.git
That normally works but it only gets to about 8 or 9 % then stalls out. Have you had this happen to you? If so, what did you do to get around it?

**Comment by Steven-Harris** [comment]
I have never had any problems like that, sorry

**Comment by thresherdj** [comment]
Hmm, just tried to down load it as a zip and it failed like that too. If I can't find a way to get external data into the VM the whole exercise is rather pointless. :-(

**Comment by thresherdj** [comment]
It looks like I could use a shared folder. The VM seems to have access to my home folder, but I can't remember how to get access to it from inside the VM, Do you know/remember?

**Comment by Steven-Harris** [comment]
You should not have to do that. Sadly, I have never got this vagrant VM to work well with shared folders

**Comment by thresherdj** [comment]
I don't get why I can clone. @megahirt do you have any ideas why I can't git clone inside the Vagrant VM?

**Comment by thresherdj** [comment]
Just tried again, I get this:
Cloning into 'rapuma'...
remote: Counting objects: 14834, done.
remote: Compressing objects: 100% (16/16), done.
error: RPC failed; result=56, HTTP code = 200B | 702.00 KiB/s  
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by thresherdj** [comment]
I tried the same thing in a normal terminal and it worked fine.

**Comment by Steven-Harris** [comment]
I would try installing the vm one more time. I think there is a firewall built-in (I would need to get on the vm to tell you what software pack it is) and you could check its config for 22,21 ports being open. 

The only other thing that you could try is stilling the app with the anisble installer in our repo. But that might be more of the long way around and I know you have already spent a lot of time on it.

**Comment by thresherdj** [comment]
Stand down everyone, it works now. I connected on a different network and it works now. Not sure why but I really don't want to know. :-)

**Comment by thresherdj** [comment]
@Steven-Harris, I just pushed to the personal/dennis branch a modified version of the setup that should help you install Rapuma easier in your server environment. I've tested it a bit and it seems to work, let me know how it goes for you.

**Comment by thresherdj** [comment]
BTW, check the installme document for new parameters used with setup.py.

**Comment by Steven-Harris** [comment]
Awesome! Thank you so much. I will let you know how it goes.

**Comment by thresherdj** [comment]
@Steven-Harris , way above in this thread, you wrote:
"Yep. I am actually using the publishing folder at /var/lib/Rapuma/publishing and then overriding the renders to another location. It will probably stay like that usually I get told otherwise."

What is that location and is it consistent? I'm working on a slight enhancement that will make it easier to keep track of the Publishing folder. I should be able to put it wherever you want it so just let me know. Thanks!

**Comment by Steven-Harris** [comment]
When Rapuma is ran through the www-data user it makes the Rapuma publishing folder at /var/lib/rapuma/. Rapuma then works out of that location. I would say it to constant. 

You may want to try using our app. If you go to ~/src/web-scripture forge/ and check out personal/Steven you can see what we have so far. Login with admin and password. And click create project -> typesetting. Enter a name. If Rapuma is setup correctly it should create a project folder at /var/lib/rapuma with your project name. Then you should be about to click on the assets tab and click "init project" to add a sample Rapuma example. Then you can go to the typeset tab and click render. To render the pdf. 

Through this process maybe you will discover for yourself some of the issues I am having

**Comment by thresherdj** [comment]
@Steven-Harris , that sounds like a good idea, I'll give it a try.

**Comment by Steven-Harris** [comment]
@thresherdj `sudo ./setup.py install --type server` I am having trouble with is. Is that command ready to be used?

In fact, `sudo ./setup.py install --type desktop` is not working either. I made sure that I was in your branch

**Comment by Steven-Harris** [comment]
@thresherdj _facepalm_ sorry, I forgot to pull.....

**Comment by thresherdj** [comment]
It should work, it works for me. I just pushed less than an hour ago. Might
want to pull again if you haven't already.

**Comment by Steven-Harris** [comment]
@thresherdj, got it installed with your changes but I am still on a wild goose chase trying to find where rapuma is try to write files too. Any suggests on where rapuma needs files and folders?

**Comment by thresherdj** [comment]
When you follow the install and get to sudo setup.py install --type server, the set up script will put a config and publishing folder at /var/lib/rapuma. There is nothing in them at that point. However, when you run rapuma for the first time, it looks for the /var/lib/rapuma/config folder. If it finds it, it knows it is a server installation and it creates a rapuma.conf. That conf file used to contain the location of the project folder. I decided to hard code that so it can go some place else if you want it to, it makes no difference to me. So, the answer to your question is that for a server installation, it needs the config and project (publishing) folder to be at /var/lib/rapuma.

**Comment by thresherdj** [comment]
FYI, the same basic process goes if it is a desktop installation, only the locations are ~/.config/rapuma for the config file and ~/Publishing for the projects folder.

**Comment by Steven-Harris** [comment]
hmm ok I am seeing the config folder at /var/lib/rapuma but it must not be running correctly as there hasn't been a rapuma.config file made yet.

**Comment by thresherdj** [comment]
Did you run just the "rapuma" command?

**Comment by thresherdj** [comment]
I don't think I made that very clear. It used to be somewhat optional but now it kind of has to be done to make the rapuma.conf file and finish the installation.

**Comment by Steven-Harris** [comment]
yes I ran `rapuma -h` and `sudo rapuma -h``

**Comment by thresherdj** [comment]
BTW, In the VM I looked at ~/src/web-scripture forge/ and couldn't find your project. What am I missing?

**Comment by thresherdj** [comment]
when you ran rapuma -h, did it give an error?

**Comment by Steven-Harris** [comment]
Are you seeing the project at ~/src/web-scriptureforge?

**Comment by thresherdj** [comment]
If it didn't, after the version it should say "(server)". If it doesn't and says, "(desktop)", then there must be a folder at ~/.config/rapuma. Destroy that folder if it is there.

**Comment by thresherdj** [comment]
No, the folder is empty at ~/src/web-scriptureforge

**Comment by Steven-Harris** [comment]
funny thing I installed using server but when I run rapuma with my own user it says, `Version v0.7.197 testing(20160406202905) - (desktop)`

**Comment by Steven-Harris** [comment]
hmm that VagrantFile was for our project so I am not sure why didn't copy. our project is located here https://github.com/sil-student-projects/web-scriptureforge

run 

`mkdir ~/src && git clone --recursive-submodules https://github.com/sil-student-projects/web-scriptureforge`

there is a developer install file to install it.  if you have the time

**Comment by thresherdj** [comment]
The folder is residual from the last install. I should probably add some code that will seek and destroy the desktop config folder if it is a server installation and vice versa.

**Comment by Steven-Harris** [comment]
oh ok, I will see if uninstalling and installing helps

**Comment by thresherdj** [comment]
Thanks for the instructions. I'll try them tomorrow when I get a chance.

**Comment by thresherdj** [comment]
Yes, uninstalling thoroughly is important. I'll try to clean that up so it isn't as necessary. I'll have to think about it a bit.

**Comment by thresherdj** [comment]
For now, I better get going. I'm about to turn into a pumpkin. :-)

**Comment by thresherdj** [comment]
@Steven-Harris - I started a new issue for the Vagrant VM not installing right. Please take a look at that when you get a chance and let me know what I should do.

**Comment by Steven-Harris** [comment]
@thresherdj is there a way to add/change a projects adjustments from the CLI without manually editing the config file.... I see an option in the CLI but I can't seem to build the correct string of commands to execute the command.

**Comment by Steven-Harris** [comment]
@thresherdj, have you been able to make any progress with Rapuma to figure out why it's not install correctly on our server environment

**Comment by thresherdj** [comment]
@Steven-Harris There would be no way to add "adjustments" to a project. Everything has to be defined in the system. Anything that is defined, with few exceptions, can be changed via the setting command. E.g.: rapuma setting [PID] font --section [section/sub-section] --key [setting key] --value [setting value]

**Comment by thresherdj** [comment]
@Steven-Harris Re. the install issue, no, I have not had time to look into that this week. Nothing is going to happen this weekend either, but hopefully next week I can get back on it.

**Comment by Steven-Harris** [comment]
@thresherdj, I learned something today when I change the runtime user of my shell to www-data. It was trying to work out of /var/www and not /var/lib ...I believe that is were the app is also trying to create projects at but I haven't been able to create a rapuma project through the app yet. I was able to get rapuma working for the www-data in the shell.

**Comment by Steven-Harris** [comment]
@thresherdj, does this problem look familiar?
![selection_002](https://cloud.githubusercontent.com/assets/7720242/14729034/9c2dbe36-0829-11e6-8853-81e64ca80ea2.png)

If so, can you tell what I can do to fix it?

**Comment by thresherdj** [comment]
@Steven-Harris I've not see this, at least that I can recall. It would seem like a permission problem and Rapuma (XeTeX) is trying to write something where it can't.

Regarding working out of /var/lib vs. /var/www. Rapuma is seeing projects as needing to be in /var/lib but I could just as easily tell it to put them in /var/www. That would be easy. I don't know much about how permissions work in the /var/www area. Is it possible that they are separate from those in other parts of the system, like /usr? Can a program be run in /usr/local/share/rapuma and write in /var/www? Would there be special permissions needed that would be applied to Rapuma on install for the server environment? Or, would Rapuma need to be installed in /var/www instead?

**Comment by Steven-Harris** [comment]
Yes any program can write to any location provided it has permissions. I
grant www data rights to /var/www but I haven't gotten Rapuma to create a
project through the web app. The only way that works is manually though the
cli.

**Comment by thresherdj** [comment]
I think I might have found what part of the problem is. I'm working on it. Hopefully it will not take too long to fix.

**Comment by thresherdj** [comment]
I did a quick fix. Hopefully it is good to go, at least to test. Do a pull on personal/dennis to get it. Basically now, it should put server projects in /var/www/rapuma/projects if you set it up to run in a server environment. I found some overlooked code that I think was causing the problem you were having. Sorry about that. I hope I got it all now. Give it a try and let me know what you think.

**Comment by megahirt** [comment]
As long as /var/www/rapuma/projects is a configurable path and not
hard-coded... the actual project directory will be something different (but
still somewhere inside /var/www)

Chris

**Comment by Steven-Harris** [comment]
Thanks @thresherdj for working on this, I will  give it a shot. We are presenting and finishing the project on May 2nd and I am trying to get a system that I can take to the presentation working before then. Currently, I am trying to get two systems working. One is the server and one is a VM. 

The server appears to be writing to /var/www but I haven't got my web application to successfully write or create any folders. (hopefully your last fix will get it there)

The VM is able to create files and folders in it's directory which is /var/lib/rapuma. (not sure why they are different). The only problem that I am having is when I render... I get this error

> Traceback (most recent call last):
>   File "/usr/local/bin/rapuma", line 904, in <module>
>     userArguments(parser.parse_args())
>   File "/usr/local/bin/rapuma", line 616, in userArguments
>     cType = ProjSetup(sysConfig, pid).returnConfigValue('project', 'Groups/' + gid, 'cType')
>   File "/usr/local/lib/python2.7/dist-packages/rapuma/project/proj_setup.py", line 49, in **init**
>     self.projHome                       = os.path.join(os.path.expanduser(self.userConfig['Resources']['projects']), self.pid)
>   File "/usr/lib/python2.7/posixpath.py", line 75, in join
>     if b.startswith('/'):

**Comment by thresherdj** [comment]
@Steven-Harris did you update with what I pushed this morning? That line 49 in proj_setup.py shouldn't be there any more.

**Comment by Steven-Harris** [comment]
I haven't update or tried the fix yet

**Comment by thresherdj** [comment]
@megahirt the /var/www/rapuma/projects is kind of hard coded but I think I know a way around it.

**Comment by thresherdj** [comment]
@Steven-Harris well, there's your problem. :-)

**Comment by Steven-Harris** [comment]
I pulled your change on the vm and got that error. I haven't tried your
code on the server.

**Comment by Steven-Harris** [comment]
@thresherdj, I pulled you change on the server just now and I am still having troubles getting the rapuma to run from the apache environment.

However, at this point we have a working VM for our project the we can present and our project is coming to an end. So, it's ok if it does get figured out.. you might be hearing from someone else if someone else starts working on it

**Comment by thresherdj** [comment]
Hope your presentation goes well. Sorry we couldn't get it to run like it should have. I wish I could have been more help but I just don't have experience with server side stuff like that. Hope someone else can pick it up from where you left off. Blessings to you!

**Comment by thresherdj** [comment]
Ok, I'm going to close this out. In conclusion, there will continue to be a rapuma.conf file. On a desktop system it will be located at ~/.config/rapuma/rapuma.conf. On a server system it will be at /var/www/rapuma/config/rapuma.conf. The code should not reflect that. Further more, the default location of where the publishing projects folder is as follows. On desktop systems, ~/Publishing. On server systems, /var/www/rapuma/publishing. An alternate location can be set/used. The code and the install docs reflect this now. Every thing has been pushed to personal/dennis. After a little testing, it will be merged with master.
